name: Terraform

on:
  push:
    paths:
      - "azure/day-01-foundations/terraform/**"
      - ".github/workflows/terraform.yml"

  pull_request:


jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: azure/day-01-foundations/terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform formatting
        run: terraform fmt -check

          - name: Terraform Init
        run: terraform init
                  - name: Terraform Validate
        run: terraform validate
              - name: Terraform Plan
        run: terraform plan -input=false